name: rohy
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^6.0.9
  simple_shadow: ^0.3.1
  blur: ^3.1.0
  intl: ^0.18.0
  flutter_screenutil: ^5.6.1
  webview_flutter: ^4.0.5
  bloc: ^8.0.2
  firebase_core: ^2.7.0
  firebase_auth:
  equatable:
  flutter_bloc:
  google_sign_in:
  email_validator:
  curved_navigation_bar: ^1.0.3


  cupertino_icons: ^1.0.2
  fluttericon: ^2.0.0
  flutter_spinkit: ^5.1.0
  blurrycontainer: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/